version: '3'
services:
  web:
    container_name: django-docker
    platform: linux/x86_64
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code
    ports:
      - 18000:8000
    volumes:
      - ./:/code
    depends_on:
      - db

  db:
    container_name: django-docker-db
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: django_docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: django
      MYSQL_PASSWORD: password
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./mysql_conf/:/etc/mysql/conf.d/
    ports:
      - 33306:3306